import type { Metadata } from "next";
import { Poppins, Outfit, Patrick_Hand_SC } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choose what you need
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const patrick_hand = Patrick_Hand_SC({
  variable: "--font-patrick-hand",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "RWRLD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${poppins.variable} ${patrick_hand.variable} antialiased relative`}
      >
        <SidebarProvider>
          <AppSidebar />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
