import type { Metadata } from "next";
import { Permanent_Marker, Outfit, Patrick_Hand_SC } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";

const permanent_marker = Permanent_Marker({
  variable: "--font-permanent-marker",
  subsets: ["latin"],
  weight: "400",
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const patrick_hand = Patrick_Hand_SC({
  variable: "--font-patrick-hand",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "RWRLD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${permanent_marker.variable} ${patrick_hand.variable} antialiased relative bg-[url("https://framerusercontent.com/images/ZHsBzYWho4sJwqYp73X2pcgFKrc.png?width=208&height=208")]`}
      >
        <SidebarProvider>
          <AppSidebar />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
